name: Build project
on: [push, pull_request]
jobs:
  install-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test

      - name: Run linters
        run: |
          npm run lint
      - name: Run sshpass commands
        on:
          push:
            branches:
              - master
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASS }}
          port: ${{ secrets.SERVER_PORT }}
          run: |
            cat /home/llavandeira/hola
